export const FourthYear = [
  {
    id: 1,
    questionText: "Which multiple access protocol is used in standard Ethernet networks?",
    answerOptions: [
      { answerID: "a", answerText: "CSMA/CD" },
      { answerID: "b", answerText: "TDMA" },
      { answerID: "c", answerText: "ALOHA" },
      { answerID: "d", answerText: "CSMA/CA" },
    ],
    correctResponse: "a",
  },
  {
    id: 2,
    questionText: "In the context of virtual memory management, what is thrashing?",
    answerOptions: [
      { answerID: "a", answerText: "A type of CPU scheduling algorithm" },
      { answerID: "b", answerText: "A state where the system spends more time paging than executing" },
      { answerID: "c", answerText: "A technique for improving page replacement efficiency" },
      { answerID: "d", answerText: "The process of swapping inactive processes to disk" },
    ],
    correctResponse: "b",
  },
  {
    id: 3,
    questionText: "Which of the following languages is NOT context-free?",
    answerOptions: [
      { answerID: "a", answerText: "L = {a^n b^n | n ≥ 0}" },
      { answerID: "b", answerText: "L = {a^n b^n c^n | n ≥ 0}" },
      { answerID: "c", answerText: "L = {a^n b^m | n, m ≥ 0}" },
      { answerID: "d", answerText: "L = {a^n b^2n | n ≥ 0}" },
    ],
    correctResponse: "b",
  },
  {
    id: 4,
    questionText: "Which phase of a compiler performs constant folding and dead code elimination?",
    answerOptions: [
      { answerID: "a", answerText: "Lexical analysis" },
      { answerID: "b", answerText: "Syntax analysis" },
      { answerID: "c", answerText: "Semantic analysis" },
      { answerID: "d", answerText: "Code optimization" },
    ],
    correctResponse: "d",
  },
  {
    id: 5,
    questionText: "What is the purpose of the Translation Lookaside Buffer (TLB) in a CPU?",
    answerOptions: [
      { answerID: "a", answerText: "To translate assembly code to machine code" },
      { answerID: "b", answerText: "To cache virtual-to-physical address translations" },
      { answerID: "c", answerText: "To store branch prediction data" },
      { answerID: "d", answerText: "To buffer I/O operations" },
    ],
    correctResponse: "b",
  },
  {
    id: 6,
    questionText: "What is the worst-case time complexity of the Quicksort algorithm?",
    answerOptions: [
      { answerID: "a", answerText: "O(n)" },
      { answerID: "b", answerText: "O(n log n)" },
      { answerID: "c", answerText: "O(n²)" },
      { answerID: "d", answerText: "O(2ⁿ)" },
    ],
    correctResponse: "c",
  },
  {
    id: 7,
    questionText: "Which of the following is not a property of a relational database?",
    answerOptions: [
      { answerID: "a", answerText: "Atomicity" },
      { answerID: "b", answerText: "Consistency" },
      { answerID: "c", answerText: "Duplication" },
      { answerID: "d", answerText: "Durability" },
    ],
    correctResponse: "c",
  },  
  {
    id: 8,
    questionText: "What is the shortest path problem that the Bellman-Ford algorithm can solve but Dijkstra's algorithm cannot?",
    answerOptions: [
      { answerID: "a", answerText: "Paths in unweighted graphs" },
      { answerID: "b", answerText: "Paths in graphs with negative weight edges" },
      { answerID: "c", answerText: "Paths in directed acyclic graphs" },
      { answerID: "d", answerText: "Paths in graphs with cycles" },
    ],
    correctResponse: "b",
  },
  {
    id: 9,
    questionText: "In the TCP/IP protocol suite, which layer is responsible for end-to-end communication and reliability?",
    answerOptions: [
      { answerID: "a", answerText: "Network Access Layer" },
      { answerID: "b", answerText: "Internet Layer" },
      { answerID: "c", answerText: "Transport Layer" },
      { answerID: "d", answerText: "Application Layer" },
    ],
    correctResponse: "c",
  },
 {
    id: 10,
    questionText: "What type of join retrieves all records from the left table and matching records from the right table?",
    answerOptions: [
      { answerID: "a", answerText: "Inner Join" },
      { answerID: "b", answerText: "Left Join" },
      { answerID: "c", answerText: "Right Join" },
      { answerID: "d", answerText: "Full Outer Join" },
    ],
    correctResponse: "b",
  },
  {
    id: 11,
    questionText: "What does the pumping lemma for regular languages help to prove?",
    answerOptions: [
      { answerID: "a", answerText: "That a language is regular" },
      { answerID: "b", answerText: "That a language is not regular" },
      { answerID: "c", answerText: "That a language is context-free" },
      { answerID: "d", answerText: "That a language is decidable" },
    ],
    correctResponse: "b",
  },
  {
    id: 12,
    questionText: "Which of the following is NOT a phase in a typical compiler?",
    answerOptions: [
      { answerID: "a", answerText: "Register allocation" },
      { answerID: "b", answerText: "Type inference" },
      { answerID: "c", answerText: "Database normalization" },
      { answerID: "d", answerText: "Instruction selection" },
    ],
    correctResponse: "c",
  },
  {
    id: 13,
    questionText: "Which of the following anomalies is addressed by database normalization?",
    answerOptions: [
      { answerID: "a", answerText: "Insertion Anomaly" },
      { answerID: "b", answerText: "Deletion Anomaly" },
      { answerID: "c", answerText: "Updation Anomaly" },
      { answerID: "d", answerText: "All of the above" },
    ],
    correctResponse: "d",
  },
  {
    id: 14,
    questionText: "Which of the following is NOT a property of a B-tree data structure?",
    answerOptions: [
      { answerID: "a", answerText: "All leaf nodes are at the same level" },
      { answerID: "b", answerText: "A node can have at most one parent" },
      { answerID: "c", answerText: "The tree must be perfectly balanced at all times" },
      { answerID: "d", answerText: "Every node except the root must be at least half full" },
    ],
    correctResponse: "c",
  },
  {
    id: 15,
    questionText: "What principle states that a subclass should be substitutable for its superclass without affecting program correctness?",
    answerOptions: [
      { answerID: "a", answerText: "Interface Segregation Principle" },
      { answerID: "b", answerText: "Liskov Substitution Principle" },
      { answerID: "c", answerText: "Dependency Inversion Principle" },
      { answerID: "d", answerText: "Single Responsibility Principle" },
    ],
    correctResponse: "b",
  },
  {
    id: 16,
    questionText: "Which routing protocol uses the Bellman-Ford algorithm?",
    answerOptions: [
      { answerID: "a", answerText: "OSPF (Open Shortest Path First)" },
      { answerID: "b", answerText: "RIP (Routing Information Protocol)" },
      { answerID: "c", answerText: "BGP (Border Gateway Protocol)" },
      { answerID: "d", answerText: "IS-IS (Intermediate System to Intermediate System)" },
    ],
    correctResponse: "b",
  },
  {
    id: 17,
    questionText: "What problem does the banker's algorithm solve in operating systems?",
    answerOptions: [
      { answerID: "a", answerText: "Process scheduling" },
      { answerID: "b", answerText: "Memory fragmentation" },
      { answerID: "c", answerText: "Deadlock avoidance" },
      { answerID: "d", answerText: "File system optimization" },
    ],
    correctResponse: "c",
  },
  {
    id: 18,
    questionText: "Which of the following describes a non-deterministic pushdown automaton (NPDA)?",
    answerOptions: [
      { answerID: "a", answerText: "A finite automaton with multiple start states" },
      { answerID: "b", answerText: "A Turing machine with limited tape movements" },
      { answerID: "c", answerText: "A finite control with a stack that can make choices at each step" },
      { answerID: "d", answerText: "A linear bounded automaton with a single tape" },
    ],
    correctResponse: "c",
  },
  {
    id: 19,
    questionText: "What technique is used to eliminate left recursion in context-free grammars?",
    answerOptions: [
      { answerID: "a", answerText: "LL(1) parsing" },
      { answerID: "b", answerText: "Left factoring" },
      { answerID: "c", answerText: "Converting to Chomsky Normal Form" },
      { answerID: "d", answerText: "Introducing new non-terminals and rewriting productions" },
    ],
    correctResponse: "d",
  },
  {
    id: 20,
    questionText: "What is the primary purpose of SIMD (Single Instruction, Multiple Data) in modern processors?",
    answerOptions: [
      { answerID: "a", answerText: "To execute multiple different instructions simultaneously" },
      { answerID: "b", answerText: "To perform the same operation on multiple data elements in parallel" },
      { answerID: "c", answerText: "To improve branch prediction accuracy" },
      { answerID: "d", answerText: "To reduce power consumption during idle states" },
    ],
    correctResponse: "b",
  },
  {
    id: 21,
    questionText: "Which normal form ensures that there are no partial dependencies in a table?",
    answerOptions: [
      { answerID: "a", answerText: "1NF" },
      { answerID: "b", answerText: "2NF" },
      { answerID: "c", answerText: "3NF" },
      { answerID: "d", answerText: "BCNF" },
    ],
    correctResponse: "b",
  },
 {
    id: 22,
    questionText: "What is the primary function of an ACID-compliant transaction?",
    answerOptions: [
      { answerID: "a", answerText: "Ensuring system security" },
      { answerID: "b", answerText: "Providing a graphical interface" },
      { answerID: "c", answerText: "Ensuring reliable database operations" },
      { answerID: "d", answerText: "Enhancing query speed" },
    ],
    correctResponse: "c",
  },
  {
    id: 23,
    questionText: "What is the purpose of NAT (Network Address Translation) in IP networks?",
    answerOptions: [
      { answerID: "a", answerText: "To encrypt network traffic" },
      { answerID: "b", answerText: "To enable the use of private IP addresses with public Internet" },
      { answerID: "c", answerText: "To establish secure VPN connections" },
      { answerID: "d", answerText: "To accelerate DNS lookups" },
    ],
    correctResponse: "b",
  },
  {
    id: 24,
    questionText: "Which memory allocation problem occurs when small free memory blocks remain unused because they are too small to satisfy any request?",
    answerOptions: [
      { answerID: "a", answerText: "External fragmentation" },
      { answerID: "b", answerText: "Internal fragmentation" },
      { answerID: "c", answerText: "Memory leakage" },
      { answerID: "d", answerText: "Page thrashing" },
    ],
    correctResponse: "a",
  },
  {
    id: 25,
    questionText: "Which of the following problems is undecidable?",
    answerOptions: [
      { answerID: "a", answerText: "Determining if a context-free grammar generates an empty language" },
      { answerID: "b", answerText: "Determining if a deterministic finite automaton accepts any string" },
      { answerID: "c", answerText: "Determining if a Turing machine halts on all inputs" },
      { answerID: "d", answerText: "Determining if a regular expression matches any string" },
    ],
    correctResponse: "c",
  },
  {
    id: 26,
    questionText: "What optimization technique involves removing common subexpressions in compiler-generated code?",
    answerOptions: [
      { answerID: "a", answerText: "Loop unrolling" },
      { answerID: "b", answerText: "Common subexpression elimination" },
      { answerID: "c", answerText: "Register allocation" },
      { answerID: "d", answerText: "Function inlining" },
    ],
    correctResponse: "b",
  },
  {
    id: 27,
    questionText: "What is the role of the Memory Management Unit (MMU) in a computer system?",
    answerOptions: [
      { answerID: "a", answerText: "To allocate CPU time to different processes" },
      { answerID: "b", answerText: "To translate virtual addresses to physical addresses" },
      { answerID: "c", answerText: "To manage the CPU cache hierarchy" },
      { answerID: "d", answerText: "To control direct memory access (DMA) operations" },
    ],
    correctResponse: "b",
  },
  {
    id: 28,
    questionText: "Which of the following SQL commands is used to remove a table completely along with its structure?",
    answerOptions: [
      { answerID: "a", answerText: "DELETE" },
      { answerID: "b", answerText: "DROP" },
      { answerID: "c", answerText: "TRUNCATE" },
      { answerID: "d", answerText: "REMOVE" },
    ],
    correctResponse: "b",
  },
  {
    id: 29,
    questionText: "What principle states that a class should have only one reason to change?",
    answerOptions: [
      { answerID: "a", answerText: "Open/Closed Principle" },
      { answerID: "b", answerText: "Single Responsibility Principle" },
      { answerID: "c", answerText: "Interface Segregation Principle" },
      { answerID: "d", answerText: "Dependency Inversion Principle" },
    ],
    correctResponse: "b",
  },
  {
    id: 30,
    questionText: "What is the purpose of the Slow Start algorithm in TCP?",
    answerOptions: [
      { answerID: "a", answerText: "To prevent network congestion by gradually increasing the sending rate" },
      { answerID: "b", answerText: "To ensure reliable packet delivery by enforcing a minimum transmission speed" },
      { answerID: "c", answerText: "To synchronize communication between sender and receiver" },
      { answerID: "d", answerText: "To reduce power consumption by slowing down inactive connections" },
    ],
    correctResponse: "a",
  },
  {
    id: 31,
    questionText: "Which scheduling algorithm is most likely to cause starvation?",
    answerOptions: [
      { answerID: "a", answerText: "Round Robin" },
      { answerID: "b", answerText: "First-Come, First-Served" },
      { answerID: "c", answerText: "Shortest Job First (non-preemptive)" },
      { answerID: "d", answerText: "Priority Scheduling (without aging)" },
    ],
    correctResponse: "d",
  },
  {
    id: 32,
    questionText: "Which of the following is TRUE about a deterministic context-free language (DCFL)?",
    answerOptions: [
      { answerID: "a", answerText: "It can always be recognized by a deterministic finite automaton" },
      { answerID: "b", answerText: "It is a proper subset of context-free languages" },
      { answerID: "c", answerText: "It cannot contain any ambiguous grammar" },
      { answerID: "d", answerText: "It is equivalent to the set of regular languages" },
    ],
    correctResponse: "b",
  },
  {
    id: 33,
    questionText: "What is the purpose of static single assignment (SSA) form in compiler design?",
    answerOptions: [
      { answerID: "a", answerText: "To eliminate runtime type checking" },
      { answerID: "b", answerText: "To simplify and improve the effectiveness of many compiler optimizations" },
      { answerID: "c", answerText: "To convert high-level code directly to machine code" },
      { answerID: "d", answerText: "To enforce strong typing in dynamically typed languages" },
    ],
    correctResponse: "b",
  },
  {
    id: 34,
    questionText: "Which indexing method stores the entire index in main memory to speed up searches?",
    answerOptions: [
      { answerID: "a", answerText: "Dense Index" },
      { answerID: "b", answerText: "Sparse Index" },
      { answerID: "c", answerText: "Clustered Index" },
      { answerID: "d", answerText: "Hash Index" },
    ],
    correctResponse: "a",
  },
  {
    id: 35,
    questionText: "Which SQL clause is used to filter records before grouping is applied?",
    answerOptions: [
      { answerID: "a", answerText: "WHERE" },
      { answerID: "b", answerText: "HAVING" },
      { answerID: "c", answerText: "GROUP BY" },
      { answerID: "d", answerText: "ORDER BY" },
    ],
    correctResponse: "a",
  },
  {
    id: 36,
    questionText: "What is the purpose of a foreign key in a relational database?",
    answerOptions: [
      { answerID: "a", answerText: "To ensure referential integrity" },
      { answerID: "b", answerText: "To store large binary data" },
      { answerID: "c", answerText: "To speed up queries" },
      { answerID: "d", answerText: "To create a primary key automatically" },
    ],
    correctResponse: "a",
  },  {
    id: 37,
    questionText: "Which of the following concurrency control mechanisms is not based on locking?",
    answerOptions: [
      { answerID: "a", answerText: "Two-phase locking" },
      { answerID: "b", answerText: "Timestamp ordering" },
      { answerID: "c", answerText: "Strict two-phase locking" },
      { answerID: "d", answerText: "Shared and Exclusive locks" },
    ],
    correctResponse: "b",
  },
  {
    id: 38,
    questionText: "Which of the following is NOT a typical page replacement algorithm used in virtual memory systems?",
    answerOptions: [
      { answerID: "a", answerText: "Least Recently Used (LRU)" },
      { answerID: "b", answerText: "First-In-First-Out (FIFO)" },
      { answerID: "c", answerText: "Banker's Algorithm" },
      { answerID: "d", answerText: "Clock Algorithm" },
    ],
    correctResponse: "c",
  },
  {
    id: 39,
    questionText: "Which of the following statements about the P vs NP problem is TRUE?",
    answerOptions: [
      { answerID: "a", answerText: "P = NP has been proven" },
      { answerID: "b", answerText: "P ≠ NP has been proven" },
      { answerID: "c", answerText: "If a problem is in NP, then there exists a polynomial-time algorithm to solve it" },
      { answerID: "d", answerText: "If P = NP, then every problem in NP could be solved in polynomial time" },
    ],
    correctResponse: "d",
  },
  {
    id: 40,
    questionText: "What is the purpose of the Copy-on-Write (CoW) technique in operating systems?",
    answerOptions: [
      { answerID: "a", answerText: "To ensure all file copies are synchronized" },
      { answerID: "b", answerText: "To defer copying of data until it is modified, sharing the original until then" },
      { answerID: "c", answerText: "To prevent unauthorized copying of protected files" },
      { answerID: "d", answerText: "To accelerate file copying operations across network storage" },
    ],
    correctResponse: "b",
  },
  {
    id: 41,
    questionText: "Which of the following is used to enforce constraints at the database level to maintain data integrity?",
    answerOptions: [
      { answerID: "a", answerText: "Triggers" },
      { answerID: "b", answerText: "Indexes" },
      { answerID: "c", answerText: "Stored Procedures" },
      { answerID: "d", answerText: "Views" },
    ],
    correctResponse: "a",
  },
  {
    id: 42,
    questionText: "What is the worst-case space complexity of a hash table with chaining to handle collisions?",
    answerOptions: [
      { answerID: "a", answerText: "O(1)" },
      { answerID: "b", answerText: "O(log n)" },
      { answerID: "c", answerText: "O(n)" },
      { answerID: "d", answerText: "O(n²)" },
    ],
    correctResponse: "c",
  },
  {
    id: 43,
    questionText: "Which normal form ensures that a table is free from transitive dependencies?",
    answerOptions: [
      { answerID: "a", answerText: "1NF" },
      { answerID: "b", answerText: "2NF" },
      { answerID: "c", answerText: "3NF" },
      { answerID: "d", answerText: "BCNF" },
    ],
    correctResponse: "c",
  },
  {
    id: 44,
    questionText: "Which protocol would be most efficient for streaming real-time video with acceptable packet loss?",
    answerOptions: [
      { answerID: "a", answerText: "TCP" },
      { answerID: "b", answerText: "UDP" },
      { answerID: "c", answerText: "HTTP" },
      { answerID: "d", answerText: "FTP" },
    ],
    correctResponse: "b",
  },
  {
    id: 45,
    questionText: "What is the Spinlock synchronization mechanism primarily used for?",
    answerOptions: [
      { answerID: "a", answerText: "Preventing context switches when waiting for a lock" },
      { answerID: "b", answerText: "Managing file system permissions" },
      { answerID: "c", answerText: "Sharing CPU time between processes" },
      { answerID: "d", answerText: "Avoiding deadlocks in database transactions" },
    ],
    correctResponse: "a",
  }
]