export const ThirdYear = [
  {
    id: 1,
    questionText: "What algorithm is commonly used for finding the minimum spanning tree of a graph?",
    answerOptions: [
      { answerID: "a", answerText: "Dijkstra's algorithm" },
      { answerID: "b", answerText: "Kruskal's algorithm" },
      { answerID: "c", answerText: "Floyd-Warshall algorithm" },
      { answerID: "d", answerText: "A* search algorithm" },
    ],
    correctResponse: "b",
  },
  {
    id: 2,
    questionText: "Which sorting algorithm has the best average-case time complexity?",
    answerOptions: [
      { answerID: "a", answerText: "Bubble Sort" },
      { answerID: "b", answerText: "Insertion Sort" },
      { answerID: "c", answerText: "Merge Sort" },
      { answerID: "d", answerText: "Selection Sort" },
    ],
    correctResponse: "c",
  },
  {
    id: 3,
    questionText: "What is the purpose of the ARP protocol in computer networks?",
    answerOptions: [
      { answerID: "a", answerText: "To map IP addresses to MAC addresses" },
      { answerID: "b", answerText: "To assign IP addresses dynamically" },
      { answerID: "c", answerText: "To encrypt network traffic" },
      { answerID: "d", answerText: "To resolve domain names to IP addresses" },
    ],
    correctResponse: "a",
  },
  {
    id: 4,
    questionText: "What OS concept ensures that multiple processes cannot use the same resource simultaneously?",
    answerOptions: [
      { answerID: "a", answerText: "Virtual memory" },
      { answerID: "b", answerText: "Mutual exclusion" },
      { answerID: "c", answerText: "Time-sharing" },
      { answerID: "d", answerText: "Spooling" },
    ],
    correctResponse: "b",
  },
  {
    id: 5,
    questionText: "Which data structure would be most efficient for implementing a dictionary?",
    answerOptions: [
      { answerID: "a", answerText: "Array" },
      { answerID: "b", answerText: "Linked List" },
      { answerID: "c", answerText: "Hash Table" },
      { answerID: "d", answerText: "Stack" },
    ],
    correctResponse: "c",
  },
  {
    id: 6,
    questionText: "What is pipelining in computer architecture?",
    answerOptions: [
      { answerID: "a", answerText: "A technique to increase memory capacity" },
      { answerID: "b", answerText: "A method for improving CPU performance by overlapping instruction execution" },
      { answerID: "c", answerText: "A network data transfer protocol" },
      { answerID: "d", answerText: "A disk scheduling algorithm" },
    ],
    correctResponse: "b",
  },
  {
    id: 7,
    questionText: "In DBMS, what does ACID stand for?",
    answerOptions: [
      { answerID: "a", answerText: "Atomicity, Consistency, Isolation, Durability" },
      { answerID: "b", answerText: "Association, Connection, Integration, Data" },
      { answerID: "c", answerText: "Authentication, Confirmation, Identification, Distribution" },
      { answerID: "d", answerText: "Adaptive, Collaborative, Integrated, Distributed" },
    ],
    correctResponse: "a",
  },
  {
    id: 8,
    questionText: "Which layer of the OSI model is responsible for logical addressing and routing?",
    answerOptions: [
      { answerID: "a", answerText: "Data Link Layer" },
      { answerID: "b", answerText: "Network Layer" },
      { answerID: "c", answerText: "Transport Layer" },
      { answerID: "d", answerText: "Session Layer" },
    ],
    correctResponse: "b",
  },
  {
    id: 9,
    questionText: "What is the primary purpose of a lexical analyzer in a compiler?",
    answerOptions: [
      { answerID: "a", answerText: "To optimize the generated code" },
      { answerID: "b", answerText: "To convert source code into tokens" },
      { answerID: "c", answerText: "To generate the final machine code" },
      { answerID: "d", answerText: "To check for semantic errors" },
    ],
    correctResponse: "b",
  },
  {
    id: 10,
    questionText: "What is the main difference between process and thread?",
    answerOptions: [
      { answerID: "a", answerText: "Processes share memory space while threads don't" },
      { answerID: "b", answerText: "Threads share memory space while processes don't" },
      { answerID: "c", answerText: "Processes are faster than threads" },
      { answerID: "d", answerText: "Threads can only exist in single-core systems" },
    ],
    correctResponse: "b",
  },
  {
    id: 11,
    questionText: "What is the key characteristic of a regular language?",
    answerOptions: [
      { answerID: "a", answerText: "It can be recognized by a Turing machine" },
      { answerID: "b", answerText: "It can be recognized by a deterministic finite automaton" },
      { answerID: "c", answerText: "It can process recursively nested structures" },
      { answerID: "d", answerText: "It requires infinite memory to process" },
    ],
    correctResponse: "b",
  },
  {
    id: 12,
    questionText: "Which of the following is a valid IPv4 address?",
    answerOptions: [
      { answerID: "a", answerText: "192.168.300.1" },
      { answerID: "b", answerText: "2001:0db8:85a3:0000:0000:8a2e:0370:7334" },
      { answerID: "c", answerText: "172.16.254.1" },
      { answerID: "d", answerText: "256.0.0.1" },
    ],
    correctResponse: "c",
  },
  {
    id: 13,
    questionText: "What is the time complexity of binary search on a sorted array?",
    answerOptions: [
      { answerID: "a", answerText: "O(1)" },
      { answerID: "b", answerText: "O(log n)" },
      { answerID: "c", answerText: "O(n)" },
      { answerID: "d", answerText: "O(n log n)" },
    ],
    correctResponse: "b",
  },
  {
    id: 14,
    questionText: "Which database index structure uses a balanced tree?",
    answerOptions: [
      { answerID: "a", answerText: "Hash index" },
      { answerID: "b", answerText: "B+ tree index" },
      { answerID: "c", answerText: "Bitmap index" },
      { answerID: "d", answerText: "Linear index" },
    ],
    correctResponse: "b",
  },
  {
    id: 15,
    questionText: "What does the cache coherence problem address in multiprocessor systems?",
    answerOptions: [
      { answerID: "a", answerText: "How to maximize cache size" },
      { answerID: "b", answerText: "How to ensure consistency of shared data across multiple caches" },
      { answerID: "c", answerText: "How to allocate cache memory efficiently" },
      { answerID: "d", answerText: "How to reduce cache miss rates" },
    ],
    correctResponse: "b",
  },
  {
    id: 16,
    questionText: "What is the main purpose of the Domain Name System (DNS)?",
    answerOptions: [
      { answerID: "a", answerText: "To encrypt domain data" },
      { answerID: "b", answerText: "To assign IP addresses to new devices" },
      { answerID: "c", answerText: "To translate domain names to IP addresses" },
      { answerID: "d", answerText: "To authenticate network users" },
    ],
    correctResponse: "c",
  },
  {
    id: 17,
    questionText: "Which algorithm is used to prevent the count-to-infinity problem in distance vector routing?",
    answerOptions: [
      { answerID: "a", answerText: "Split horizon" },
      { answerID: "b", answerText: "Link state routing" },
      { answerID: "c", answerText: "Flood routing" },
      { answerID: "d", answerText: "Source routing" },
    ],
    correctResponse: "a",
  },
  {
    id: 18,
    questionText: "What is the purpose of the semaphore synchronization primitive?",
    answerOptions: [
      { answerID: "a", answerText: "To count available system resources" },
      { answerID: "b", answerText: "To encrypt inter-process messages" },
      { answerID: "c", answerText: "To enable process scheduling" },
      { answerID: "d", answerText: "To manage virtual memory" },
    ],
    correctResponse: "a",
  },
  {
    id: 19,
    questionText: "What differentiates a compiler from an interpreter?",
    answerOptions: [
      { answerID: "a", answerText: "Compilers are faster than interpreters" },
      { answerID: "b", answerText: "Compilers translate entire programs before execution" },
      { answerID: "c", answerText: "Interpreters can handle more complex languages" },
      { answerID: "d", answerText: "Interpreters produce executable files" },
    ],
    correctResponse: "b",
  },
  {
    id: 20,
    questionText: "What is the primary goal of normalization in database design?",
    answerOptions: [
      { answerID: "a", answerText: "To improve query performance" },
      { answerID: "b", answerText: "To reduce storage requirements" },
      { answerID: "c", answerText: "To minimize data redundancy" },
      { answerID: "d", answerText: "To simplify database security" },
    ],
    correctResponse: "c",
  },
  {
    id: 21,
    questionText: "What is the main function of a CPU's control unit?",
    answerOptions: [
      { answerID: "a", answerText: "To perform arithmetic operations" },
      { answerID: "b", answerText: "To store program instructions" },
      { answerID: "c", answerText: "To direct operations of the entire processor" },
      { answerID: "d", answerText: "To manage input/output devices" },
    ],
    correctResponse: "c",
  },
  {
    id: 22,
    questionText: "Which data structure is best suited for implementing a priority queue?",
    answerOptions: [
      { answerID: "a", answerText: "Array" },
      { answerID: "b", answerText: "Linked List" },
      { answerID: "c", answerText: "Heap" },
      { answerID: "d", answerText: "Stack" },
    ],
    correctResponse: "c",
  },
  {
    id: 23,
    questionText: "What is the purpose of the TCP three-way handshake?",
    answerOptions: [
      { answerID: "a", answerText: "To authenticate users" },
      { answerID: "b", answerText: "To establish a reliable connection" },
      { answerID: "c", answerText: "To encrypt the data transmission" },
      { answerID: "d", answerText: "To compress data before transmission" },
    ],
    correctResponse: "b",
  },
  {
    id: 24,
    questionText: "What is the primary purpose of a parse tree in compiler design?",
    answerOptions: [
      { answerID: "a", answerText: "To represent the lexical structure of a program" },
      { answerID: "b", answerText: "To optimize code execution" },
      { answerID: "c", answerText: "To represent the grammatical structure of a program" },
      { answerID: "d", answerText: "To detect runtime errors" },
    ],
    correctResponse: "c",
  },
  {
    id: 25,
    questionText: "Which of the following is a characteristic of a context-free grammar?",
    answerOptions: [
      { answerID: "a", answerText: "All production rules have exactly one non-terminal on the left side" },
      { answerID: "b", answerText: "Production rules can depend on neighboring symbols" },
      { answerID: "c", answerText: "It cannot generate recursive structures" },
      { answerID: "d", answerText: "It is less powerful than regular grammars" },
    ],
    correctResponse: "a",
  },
  {
    id: 26,
    questionText: "What is dynamic binding in object-oriented programming?",
    answerOptions: [
      { answerID: "a", answerText: "The process of linking program modules at compile time" },
      { answerID: "b", answerText: "The process of determining which method to invoke at runtime" },
      { answerID: "c", answerText: "A technique for optimizing memory allocation" },
      { answerID: "d", answerText: "A method for initializing variables dynamically" },
    ],
    correctResponse: "b",
  },
  {
    id: 27,
    questionText: "What is the main purpose of DHCP in computer networks?",
    answerOptions: [
      { answerID: "a", answerText: "To secure network communications" },
      { answerID: "b", answerText: "To automatically assign IP addresses to devices" },
      { answerID: "c", answerText: "To filter network traffic" },
      { answerID: "d", answerText: "To translate domain names to IP addresses" },
    ],
    correctResponse: "b",
  },
  {
    id: 28,
    questionText: "What is the key feature of a hierarchical database model?",
    answerOptions: [
      { answerID: "a", answerText: "Data is organized in tables with columns and rows" },
      { answerID: "b", answerText: "Data is represented as a collection of objects" },
      { answerID: "c", answerText: "Data is organized in a tree-like structure" },
      { answerID: "d", answerText: "Data is stored in key-value pairs" },
    ],
    correctResponse: "c",
  },
  {
    id: 29,
    questionText: "What is the principle behind a Harvard architecture in computer design?",
    answerOptions: [
      { answerID: "a", answerText: "Using separate storage and signal pathways for instructions and data" },
      { answerID: "b", answerText: "Combining CPU and memory on a single chip" },
      { answerID: "c", answerText: "Using multiple processors in parallel" },
      { answerID: "d", answerText: "Implementing variable-length instructions" },
    ],
    correctResponse: "a",
  },
  {
    id: 30,
    questionText: "What is the main advantage of Red-Black trees over binary search trees?",
    answerOptions: [
      { answerID: "a", answerText: "They use less memory" },
      { answerID: "b", answerText: "They guarantee better worst-case time complexity for operations" },
      { answerID: "c", answerText: "They can store more data" },
      { answerID: "d", answerText: "They support multi-threaded access" },
    ],
    correctResponse: "b",
  },
  {
    id: 31,
    questionText: "What is a subnet mask used for in IP networking?",
    answerOptions: [
      { answerID: "a", answerText: "To encrypt IP addresses" },
      { answerID: "b", answerText: "To distinguish between the network and host portions of an IP address" },
      { answerID: "c", answerText: "To compress IP packets" },
      { answerID: "d", answerText: "To authenticate network users" },
    ],
    correctResponse: "b",
  },
  {
    id: 32,
    questionText: "What is the primary function of an operating system's scheduler?",
    answerOptions: [
      { answerID: "a", answerText: "To allocate memory to processes" },
      { answerID: "b", answerText: "To decide which process runs on the CPU and when" },
      { answerID: "c", answerText: "To manage file systems" },
      { answerID: "d", answerText: "To handle input/output operations" },
    ],
    correctResponse: "b",
  },
  {
    id: 33,
    questionText: "What is inheritance in object-oriented programming?",
    answerOptions: [
      { answerID: "a", answerText: "The ability to hide implementation details" },
      { answerID: "b", answerText: "The ability to reuse code by extending existing classes" },
      { answerID: "c", answerText: "The ability to create multiple instances of a class" },
      { answerID: "d", answerText: "The ability to override methods at runtime" },
    ],
    correctResponse: "b",
  },
  {
    id: 34,
    questionText: "What is the purpose of a link register in a CPU?",
    answerOptions: [
      { answerID: "a", answerText: "To store intermediate results of calculations" },
      { answerID: "b", answerText: "To store the return address during function calls" },
      { answerID: "c", answerText: "To establish connections between memory blocks" },
      { answerID: "d", answerText: "To track the status of I/O devices" },
    ],
    correctResponse: "b",
  },
  {
    id: 35,
    questionText: "What is the purpose of a syntax-directed translation scheme?",
    answerOptions: [
      { answerID: "a", answerText: "To check for lexical errors" },
      { answerID: "b", answerText: "To generate intermediate code based on grammar rules" },
      { answerID: "c", answerText: "To optimize machine code" },
      { answerID: "d", answerText: "To detect runtime errors" },
    ],
    correctResponse: "b",
  },
  {
    id: 36,
    questionText: "What is a deadlock in operating systems?",
    answerOptions: [
      { answerID: "a", answerText: "A situation where a process is terminated unexpectedly" },
      { answerID: "b", answerText: "A situation where processes are waiting for each other to release resources" },
      { answerID: "c", answerText: "A security breach where unauthorized processes gain access" },
      { answerID: "d", answerText: "A memory leak that gradually consumes system resources" },
    ],
    correctResponse: "b",
  },
  {
    id: 37,
    questionText: "What is the RAID storage technology primarily designed to provide?",
    answerOptions: [
      { answerID: "a", answerText: "Data compression" },
      { answerID: "b", answerText: "Increased storage capacity only" },
      { answerID: "c", answerText: "Improved performance and/or data redundancy" },
      { answerID: "d", answerText: "Enhanced encryption capabilities" },
    ],
    correctResponse: "c",
  },
  {
    id: 38,
    questionText: "What is the main benefit of using prepared statements in database programming?",
    answerOptions: [
      { answerID: "a", answerText: "They make code more readable" },
      { answerID: "b", answerText: "They help prevent SQL injection attacks" },
      { answerID: "c", answerText: "They automatically optimize query performance" },
      { answerID: "d", answerText: "They reduce database size" },
    ],
    correctResponse: "b",
  },
  {
    id: 39,
    questionText: "What does the Von Neumann architecture include?",
    answerOptions: [
      { answerID: "a", answerText: "Separate paths for data and instructions" },
      { answerID: "b", answerText: "Shared memory for both data and instructions" },
      { answerID: "c", answerText: "Multiple processors working in parallel" },
      { answerID: "d", answerText: "Specialized hardware for specific tasks only" },
    ],
    correctResponse: "b",
  },
  {
    id: 40,
    questionText: "What is the primary purpose of a firewall in network security?",
    answerOptions: [
      { answerID: "a", answerText: "To accelerate network traffic" },
      { answerID: "b", answerText: "To monitor and control incoming and outgoing network traffic" },
      { answerID: "c", answerText: "To compress data for efficient transmission" },
      { answerID: "d", answerText: "To distribute network load across multiple servers" },
    ],
    correctResponse: "b",
  },
  {
    id: 41,
    questionText: "What does the term 'cache miss' refer to?",
    answerOptions: [
      { answerID: "a", answerText: "When data in cache becomes corrupted" },
      { answerID: "b", answerText: "When requested data is not found in the cache" },
      { answerID: "c", answerText: "When the cache is full and cannot store new data" },
      { answerID: "d", answerText: "When cache memory fails completely" },
    ],
    correctResponse: "b",
  },
  {
    id: 42,
    questionText: "What is the primary role of a DBMS transaction log?",
    answerOptions: [
      { answerID: "a", answerText: "To improve query performance" },
      { answerID: "b", answerText: "To provide database recovery capabilities" },
      { answerID: "c", answerText: "To store user credentials" },
      { answerID: "d", answerText: "To compress database tables" },
    ],
    correctResponse: "b",
  },
  {
    id: 43,
    questionText: "What is branch prediction in CPU design?",
    answerOptions: [
      { answerID: "a", answerText: "A technique to diagnose faulty CPU branches" },
      { answerID: "b", answerText: "A feature that attempts to guess which way a branch will go before this is known for sure" },
      { answerID: "c", answerText: "A method to eliminate conditional branches from code" },
      { answerID: "d", answerText: "A process that creates redundant execution paths" },
    ],
    correctResponse: "b",
  },
  {
    id: 44,
    questionText: "What is the primary function of SMTP in email systems?",
    answerOptions: [
      { answerID: "a", answerText: "To download emails from a server" },
      { answerID: "b", answerText: "To send emails between servers" },
      { answerID: "c", answerText: "To filter spam emails" },
      { answerID: "d", answerText: "To encrypt email content" },
    ],
    correctResponse: "b",
  },
  {
    id: 45,
    questionText: "What is the purpose of virtual memory in operating systems?",
    answerOptions: [
      { answerID: "a", answerText: "To create virtual machines" },
      { answerID: "b", answerText: "To encrypt sensitive memory areas" },
      { answerID: "c", answerText: "To allow programs to use more memory than physically available" },
      { answerID: "d", answerText: "To speed up memory access times" },
    ],
    correctResponse: "c",
  }
]